### ISSUE TITLE
Nested values may not be handled correctly?

### ISSUE THREAD

**Issue by mish15** [sajari/sdk-php#1]
Reported issue was a problem with the request below. I haven't looked, but i would guess the meta array is not being converted to the POST array Sajari expects. We probably should handle this though.

``` php
$result = $c->search(array(
        'meta'=>array(
            'specialty'=>'136',
            'sub_specialty'=>'137'
        ), 
        'maxresults' => 40,
));
$result = $c->search(array(
        "filters"=>array(
            array("specialty" => "136"),
            array("sub_specialty" => "137")
        ),
        'maxresults' => 40,
));
```

**Comment by jonathaningram** [comment]
@mish15 should be fixed. Please run `computer update sajari/sajari-sdk-php` to get the latest fix.
