### ISSUE TITLE
Allow get and remove to not need an ID

### ISSUE THREAD

**Issue by mish15** [sajari/sdk-php#11]
id is no longer required as long as a meta[id] is set, where id can be any meta field.

Note, if an ID is not used, the trailing slash should be removed as this is a different route. Prob should fix this in the engine handler also.

See https://github.com/sajari/sajari-sdk-php/blob/master/src/Sajari/Engine/EngineClient.php#L230

**Comment by jonathaningram** [comment]
Done in e69029ecf91d363231cbafaf2a33bad6b3d997ad
