### ISSUE TITLE
Support "OR:" filter prefix

### ISSUE THREAD

**Issue by mish15** [sajari/sdk-php#14]
Filters should allow a 4th component, which sets the sequential processing status. By default this is "AND", but can be changed to "OR" to allow the OR function between multiple filters. These are processed sequentially from the back, so as soon as an AND is hit, that filter must match or the filter will return false. 

Example:

```
filters=!=category,|OR:dir1,news
```

The PHP SDK should pack this accordingly for the JSON and flattened queries.

**Comment by mish15** [comment]
@dhowden need to think about nesting and potentially allowing full nesting instead of the simple combos we support now

**Comment by dhowden** [comment]
This can be achieved using the new API.
