### ISSUE TITLE
replace, remove, weight, get functions should not require ID's

### ISSUE THREAD

**Issue by mish15** [sajari/sdk-php#15]
Much like "patch", it's possible to use a meta ID instead of an engine ID, so these functions should not require an ID.

**Comment by jonathaningram** [comment]
@mish15 will fix it up for you.

**Comment by mish15** [comment]
@jonathaningram thanks mate!

**Comment by jonathaningram** [comment]
@mish15 for weight, currently it's `/fingerprint/weight/{id}/{pos}/{neg}` - if we allow meta ID, and I send `/fingerprint/weight/{pos}/{neg}` will Sajari know that `{pos}` is not ID? i.e. it will take pos and neg as the last 2 params.

**Comment by jonathaningram** [comment]
@mish15 to fix https://www.sajari.com/api/fingerprint/weight/1-1 response

**Comment by mish15** [comment]
@jonathaningram pending deployment. But fixed. Need to test once live (should be today or monday).

**Comment by mish15** [comment]
Fixed on API side now.
