### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by mish15** [sajari/sdk-php#2]
We need some additional examples:
- [ ] finding a document with a filter and then deleting it
- [ ] fingerprint weighting, both with a fingerprint or a profile ID (two examples)

**Comment by tbillington** [comment]
I've got examples for all the basic operations, nothing specific though.

I assume we'd want to have the same examples in all of the SDKs ( @dhowden ), so we should come up with a list of common operations that we'd want to showcase.

**Comment by tbillington** [comment]
There are snippets in the readme and working examples for record and search endpoints, so I'll close this for now. I'll add more but this issue isn't really relevant anymore.
