### ISSUE TITLE
Create new Value class

### ISSUE THREAD

**Issue by dhowden** [sajari/sdk-php#24]
Create a value class with static methods to convert proto engine.Value to and from native PHP types, i.e

`Value::FromProto($proto) -> $phpType`
`Value::ToProto($phpType) -> $proto`

This class is then used when decoding/encoding engine Keys, Record field values, etc...

**Comment by tbillington** [comment]
Implemented with https://github.com/sajari/sajari-sdk-php/commit/56a043a3afc8260b58567cb9d689a319e0d73f9d#diff-9ec7b489631d30b095d0f4fa2599dc76.

`Value` was repurposed to fit it's true use case.
