### ISSUE TITLE
Specifying an empty array for transforms should be possible.

### ISSUE THREAD

**Issue by dhowden** [sajari/sdk-php#26]
Currently you can't specify an empty array for transforms, it should be possible.

https://github.com/sajari/sajari-sdk-php/blob/master/src/Sajari/Client/Client.php#L211

Not sure how you can get around this in PHP though?  Maybe just check `isset` instead of also checking `count` (and remove the default `[]` value).

**Comment by tbillington** [comment]
Fixed by using null as the default so that we can distinguish between an intentional empty array and nothing being passed.

https://github.com/sajari/sajari-sdk-php/commit/ed5263141a03bb78b37d2a12013f3ec719ab86eb
