### ISSUE TITLE
Tag a release / Semantic Versioning

### ISSUE THREAD

**Issue by benjy** [sajari/sdk-php#6]
Can we tag a release, it would make it easier for consumers of this SDK to stick to a version and it will make compatibility with other libraries much easier in the future.

I'd recommend semantic versioning: http://semver.org/

**Comment by jonathaningram** [comment]
@benjy have tagged v0.1.0. Will keep it under 1.0.0 for a bit until we feel it's stable enough. At least this gives you a fixed point to require. That work for you?

**Comment by benjy** [comment]
Awesome, thank you.
