### ISSUE TITLE
Should there be an encodeMeta function?

### ISSUE THREAD

**Issue by benjy** [sajari/sdk-php#9]
What is the recommend way of putting the meta data into the query if there is no encodeMeta that can be passed into $data['meta']?

Should $data['meta'] simply be a string from http_build_query()

**Comment by jonathaningram** [comment]
@benjy does the usage as in https://github.com/sajari/sajari-sdk-php/blob/master/examples/1/add.php#L18 not work for your case? If not, could you please provide a bit more info/code of what call you're making.

**Comment by benjy** [comment]
@jonathaningram i'll try that, is it the same for search?

**Comment by jonathaningram** [comment]
@benjy yep should be the same for search. Let me know if this is not the case!
